/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 26-Jun-2019 12:16:34 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `comments` CASCADE
;

DROP TABLE IF EXISTS `expenses` CASCADE
;

DROP TABLE IF EXISTS `floatsheets` CASCADE
;

DROP TABLE IF EXISTS `locations` CASCADE
;

DROP TABLE IF EXISTS `overrings` CASCADE
;

DROP TABLE IF EXISTS `shops` CASCADE
;

DROP TABLE IF EXISTS `transfers` CASCADE
;

/* Create Tables */

CREATE TABLE `comments`
(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`floatsheet_id` INT UNSIGNED NOT NULL,
	`comment` NVARCHAR(300) NOT NULL,
	`name` NVARCHAR(50) NULL,
	CONSTRAINT `PK_Comments` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `expenses`
(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`floatsheet_id` INT UNSIGNED NOT NULL,
	`description` NVARCHAR(50) NOT NULL,
	`amount` DECIMAL(10,2) NOT NULL,
	CONSTRAINT `PK_Expenses` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `floatsheets`
(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`location_id` SMALLINT UNSIGNED NOT NULL,
	`fs_date` DATE NOT NULL,
	`mc_cash_50` DECIMAL(8,0) UNSIGNED NULL,
	`mc_cash_20` DECIMAL(8,0) UNSIGNED NULL,
	`mc_cash_10` DECIMAL(8,0) UNSIGNED NULL,
	`mc_cash_5` DECIMAL(8,0) UNSIGNED NULL,
	`mc_cash_2` DECIMAL(8,0) UNSIGNED NULL,
	`mc_cash_1` DECIMAL(8,0) NULL,
	`mc_cash_50p` DECIMAL(8,2) UNSIGNED NULL,
	`mc_vouchers_50` DECIMAL(8,0) UNSIGNED NULL,
	`mc_vouchers_20` DECIMAL(8,0) UNSIGNED NULL,
	`mc_vouchers_10` DECIMAL(8,0) UNSIGNED NULL,
	`mc_vouchers_5` DECIMAL(8,0) UNSIGNED NULL,
	`mc_vouchers_2` DECIMAL(8,0) UNSIGNED NULL,
	`mc_vouchers_1` DECIMAL(8,0) NULL,
	`mc_vouchers_50p` DECIMAL(8,2) UNSIGNED NULL,
	`mc_cash_change` DECIMAL(10,2) UNSIGNED NULL,
	`mc_cash_subtotal` DECIMAL(10,2) UNSIGNED NULL,
	`mc_vouchers_subtotal` DECIMAL(8,0) UNSIGNED NULL,
	`mc_cash_reserve` DECIMAL(10,2) UNSIGNED NULL,
	`mc_vouchers_reserve` DECIMAL(8,0) UNSIGNED NULL,
	`mc_cash_change_reserve` DECIMAL(10,2) UNSIGNED NULL,
	`mc_vouchers_change_reserve` DECIMAL(8,0) UNSIGNED NULL,
	`mc_cash_total` DECIMAL(10,2) UNSIGNED NULL,
	`mc_vouchers_total` DECIMAL(8,0) UNSIGNED NULL,
	`mc_completed_by` NVARCHAR(50) NULL,
	`ec_cash_pdq_total` DECIMAL(10,2) UNSIGNED NULL,
	`ec_cash_50` DECIMAL(8,0) UNSIGNED NULL,
	`ec_cash_20` DECIMAL(8,0) UNSIGNED NULL,
	`ec_cash_10` DECIMAL(8,0) UNSIGNED NULL,
	`ec_cash_5` DECIMAL(8,0) UNSIGNED NULL,
	`ec_cash_2` DECIMAL(8,0) UNSIGNED NULL,
	`ec_cash_1` DECIMAL(8,0) NULL,
	`ec_cash_50p` DECIMAL(8,2) UNSIGNED NULL,
	`ec_vouchers_pdq_total` DECIMAL(8,0) UNSIGNED NULL,
	`ec_vouchers_50` DECIMAL(8,0) UNSIGNED NULL,
	`ec_vouchers_20` DECIMAL(8,0) UNSIGNED NULL,
	`ec_vouchers_10` DECIMAL(8,0) UNSIGNED NULL,
	`ec_vouchers_5` DECIMAL(8,0) UNSIGNED NULL,
	`ec_vouchers_2` DECIMAL(8,0) UNSIGNED NULL,
	`ec_vouchers_1` DECIMAL(8,0) NULL,
	`ec_vouchers_50p` DECIMAL(8,2) UNSIGNED NULL,
	`ec_cash_change` DECIMAL(10,2) UNSIGNED NULL,
	`ec_cash_subtotal` DECIMAL(10,2) UNSIGNED NULL,
	`ec_vouchers_subtotal` DECIMAL(8,0) UNSIGNED NULL,
	`ec_cash_reserve` DECIMAL(10,2) UNSIGNED NULL,
	`ec_vouchers_reserve` DECIMAL(8,0) UNSIGNED NULL,
	`ec_cash_change_reserve` DECIMAL(10,2) UNSIGNED NULL,
	`ec_vouchers_change_reserve` DECIMAL(8,0) UNSIGNED NULL,
	`ec_cash_total` DECIMAL(10,2) UNSIGNED NULL,
	`ec_vouchers_total` DECIMAL(8,0) UNSIGNED NULL,
	`ec_completed_by` NVARCHAR(50) NULL,
	`ec_cash_less_banking` DECIMAL(10,2) NULL,
	`ec_cash_less_ccs` DECIMAL(10,2) UNSIGNED NULL,
	`ec_vouchers_less_claimed` DECIMAL(10,2) UNSIGNED NULL,
	`ec_cash_tomorrows_float` DECIMAL(10,2) UNSIGNED NULL,
	`ec_vounchers_tomorrows_float` DECIMAL(10,2) UNSIGNED NULL,
	`add_transfers_in_cash` DECIMAL(10,2) UNSIGNED NULL,
	`add_transfers_in_vouchers` DECIMAL(10,2) UNSIGNED NULL,
	`less_transfers_out_cash` DECIMAL(10,2) UNSIGNED NULL,
	`less_transfers_out_vouchers` DECIMAL(10,2) UNSIGNED NULL,
	`zreport_cash` DECIMAL(10,2) UNSIGNED NULL,
	`zreport_check` DECIMAL(10,2) UNSIGNED NULL,
	`zreport_charge` DECIMAL(10,2) UNSIGNED NULL,
	`less_sales_overrings_cash` DECIMAL(10,2) UNSIGNED NULL,
	`less_sales_overrings_vouchers` DECIMAL(10,0) UNSIGNED NULL,
	`add_other_overrings_cash` DECIMAL(10,2) UNSIGNED NULL,
	`add_other_overrings_vouchers` DECIMAL(10,0) UNSIGNED NULL,
	`check_total_cash` DECIMAL(10,2) UNSIGNED NULL,
	`check_total_vouchers` DECIMAL(10,0) UNSIGNED NULL,
	`payouts_cash` DECIMAL(10,2) NULL,
	`payouts_vouchers` DECIMAL(10,2) NULL,
	`payouts_total` DECIMAL(10,2) NULL,
	`checks_completed_by` NVARCHAR(50) NULL,
	CONSTRAINT `PK_Floatsheets` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `locations`
(
	`id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`loc_name` NVARCHAR(50) NOT NULL,
	`loc_address` NVARCHAR(70) NULL,
	`loc_floor` NVARCHAR(50) NULL,
	CONSTRAINT `PK_Shopfloors` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `overrings`
(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`floatsheet_id` INT UNSIGNED NOT NULL,
	`location_id` SMALLINT UNSIGNED NOT NULL,
	`type` NCHAR(1) NOT NULL,
	`cv` NCHAR(1) NOT NULL,
	`amount` DECIMAL(10,2) NULL,
	CONSTRAINT `PK_Overrings` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `shops`
(
	`id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` NVARCHAR(25) NOT NULL,
	`address` NVARCHAR(50) NULL,
	CONSTRAINT `PK_Shops` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `transfers`
(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`floatsheet_id` INT UNSIGNED NOT NULL,
	`from_location_id` SMALLINT UNSIGNED NOT NULL,
	`to_location_id` SMALLINT UNSIGNED NOT NULL,
	`cv` NCHAR(1) NOT NULL,
	`transfer_in` DECIMAL(10,2) NULL,
	`transfer_out` DECIMAL(10,2) NULL,
	`transfer_time` TIME NULL,
	`initials` NVARCHAR(10) NULL,
	CONSTRAINT `PK_Transfers` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `comments` 
 ADD INDEX `IXFK_Comments_Floatsheets` (`floatsheet_id` ASC)
;

ALTER TABLE `expenses` 
 ADD INDEX `IXFK_Expenses_Floatsheets` (`floatsheet_id` ASC)
;

ALTER TABLE `floatsheets` 
 ADD INDEX `IXFK_floatsheets_locations` (`location_id` ASC)
;

ALTER TABLE `overrings` 
 ADD INDEX `IXFK_Overrings_Floatsheets` (`floatsheet_id` ASC)
;

ALTER TABLE `overrings` 
 ADD INDEX `IXFK_overrings_locations` (`location_id` ASC)
;

ALTER TABLE `transfers` 
 ADD INDEX `IXFK_Transfers_Floatsheets` (`floatsheet_id` ASC)
;

ALTER TABLE `transfers` 
 ADD INDEX `IXFK_transfers_locations` (`from_location_id` ASC)
;

ALTER TABLE `transfers` 
 ADD INDEX `IXFK_transfers_locations_02` (`to_location_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `comments` 
 ADD CONSTRAINT `FK_Comments_Floatsheets`
	FOREIGN KEY (`floatsheet_id`) REFERENCES `floatsheets` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `expenses` 
 ADD CONSTRAINT `FK_Expenses_Floatsheets`
	FOREIGN KEY (`floatsheet_id`) REFERENCES `floatsheets` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `floatsheets` 
 ADD CONSTRAINT `FK_floatsheets_locations`
	FOREIGN KEY (`location_id`) REFERENCES `locations` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `overrings` 
 ADD CONSTRAINT `FK_Overrings_Floatsheets`
	FOREIGN KEY (`floatsheet_id`) REFERENCES `floatsheets` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `overrings` 
 ADD CONSTRAINT `FK_overrings_locations`
	FOREIGN KEY (`location_id`) REFERENCES `locations` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `transfers` 
 ADD CONSTRAINT `FK_Transfers_Floatsheets`
	FOREIGN KEY (`floatsheet_id`) REFERENCES `floatsheets` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `transfers` 
 ADD CONSTRAINT `FK_transfers_locations`
	FOREIGN KEY (`from_location_id`) REFERENCES `locations` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `transfers` 
 ADD CONSTRAINT `FK_transfers_locations_02`
	FOREIGN KEY (`to_location_id`) REFERENCES `locations` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
